# Generated by Django 3.2.9 on 2022-06-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
    ]
