# Generated by Django 3.2.9 on 2022-06-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220609_1157'),
    ]

    operations = [
    ]
