# Generated by Django 3.2.9 on 2022-06-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220609_1413'),
    ]

    operations = [
    ]
